"""DataPilot AI - Agentic AI-powered data analysis (Streamlit UI + agent orchestration)."""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import streamlit as st
from dotenv import load_dotenv

load_dotenv()

from agents import analyst, explainer, planner, question_analyzer, validator  # noqa: E402
from services import firestore_service as fs  # noqa: E402
from services.gemini_service import GeminiService  # noqa: E402
from utils.data_analysis import AnalysisError, format_number  # noqa: E402
from utils.data_loader import DataLoadError, dataset_info, load_csv, profile_columns  # noqa: E402

UNSUPPORTED_MESSAGE = "I couldn't answer this question using the available dataset."
SAMPLE_PATH = Path(__file__).parent / "sample_data" / "sales.csv"

st.set_page_config(page_title="DataPilot AI", page_icon="🧭", layout="wide")


@st.cache_resource
def get_gemini() -> GeminiService:
    return GeminiService()


# --------------------------------------------------------------------------- agent
def run_agent(question: str, df, gemini) -> dict:
    """Question Analyzer -> Planner -> Pandas tool -> Validator -> Gemini explanation."""
    trace: list[tuple[str, str]] = []
    profile = profile_columns(df)

    understanding = question_analyzer.analyze(question, df, profile, gemini)
    how = "Gemini" if understanding["source"] == "gemini" else "keyword rules"
    trace.append(("Question understood", f"{understanding['understood']} (interpreted with {how})"))

    plan = planner.build_plan(understanding, profile)
    trace.append(("Analysis planned", plan["description"]))

    ok, message = validator.validate_plan(plan, df)
    if not ok:
        trace.append(("Validation", f"Rejected: {message}"))
        return {"status": "unsupported", "reason": message, "trace": trace, "plan": plan}

    try:
        result = analyst.run(plan, df)
    except AnalysisError as exc:
        trace.append(("Python analysis", f"Failed: {exc}"))
        return {"status": "error", "reason": str(exc), "trace": trace, "plan": plan}
    trace.append(("Python analysis", "Pandas calculated the result; no numbers were generated by the LLM."))

    ok, message = validator.validate_result(result)
    trace.append(("Validation", message))
    if not ok:
        return {"status": "error", "reason": message, "trace": trace, "plan": plan}

    explanation = explainer.explain(question, plan, result, gemini)
    trace.append((
        "AI explanation",
        "Gemini explained the calculated result." if explanation["ai_used"]
        else "Gemini was unavailable; the computed summary is shown instead.",
    ))
    return {"status": "ok", "plan": plan, "result": result, "explanation": explanation, "trace": trace}


# --------------------------------------------------------------------------- state
def init_state():
    defaults = {
        "df": None, "dataset_name": None, "last_upload_key": None, "load_error": None,
        "result": None, "result_question": None, "save_warning": None,
        "local_history": [], "history": None, "history_error": None,
    }
    for key, value in defaults.items():
        st.session_state.setdefault(key, value)


def set_dataset(df, name: str):
    st.session_state.df, st.session_state.dataset_name = df, name
    st.session_state.result, st.session_state.load_error = None, None


def refresh_history():
    try:
        st.session_state.history = fs.get_history(limit=50)
        st.session_state.history_error = None
    except fs.FirestoreError as exc:
        st.session_state.history = list(reversed(st.session_state.local_history))
        st.session_state.history_error = str(exc)


def save_history(record: dict):
    st.session_state.local_history.append({**record, "timestamp": datetime.now(timezone.utc)})
    try:
        fs.save_analysis(record)
        st.session_state.save_warning = None
    except fs.FirestoreError as exc:
        st.session_state.save_warning = f"{exc} Showing this session's history only."
    refresh_history()


def fmt_time(ts) -> str:
    return ts.strftime("%Y-%m-%d %H:%M UTC") if hasattr(ts, "strftime") else str(ts)


# --------------------------------------------------------------------------- rendering
def render_dataset(df):
    info = dataset_info(df)
    c1, c2, c3 = st.columns(3)
    c1.metric("Rows", f"{info['rows']:,}")
    c2.metric("Columns", info["columns"])
    c3.metric("Missing values", f"{info['missing_total']:,}")
    st.markdown("**Columns:** " + ", ".join(f"`{c}`" for c in info["column_names"]))
    if info["missing_by_column"]:
        st.caption("Missing by column: " + ", ".join(f"{c}: {n}" for c, n in info["missing_by_column"].items()))
    st.markdown("**Preview**")
    st.dataframe(df.head(10), hide_index=True)


def render_result(res: dict):
    if res["status"] == "ok":
        ex, result = res["explanation"], res["result"]
        st.markdown("### Answer")
        st.write(ex["answer"])
        if ex["note"]:
            st.info(ex["note"])

        st.markdown("### Key Metrics")
        metrics = result["metrics"]
        cols = st.columns(min(len(metrics), 4) or 1)
        for i, (label, value) in enumerate(metrics.items()):
            cols[i % len(cols)].metric(label, value if isinstance(value, str) else format_number(value))
        for title, table in result["tables"]:
            st.caption(title)
            st.dataframe(table, hide_index=True)

        st.markdown("### Insights")
        if ex["insights"]:
            for insight in ex["insights"]:
                st.markdown(f"- {insight}")
        else:
            st.write("No additional insights for this question.")

        st.markdown("### Recommendation")
        st.write(ex["recommendation"] or "No specific recommendation for this question.")
    else:
        st.warning(UNSUPPORTED_MESSAGE)
        st.caption(f"Reason: {res['reason']}")

    with st.expander("How the Agent Worked"):
        st.caption("Question → Planning → Pandas Analysis → Validation → AI Explanation")
        for i, (title, detail) in enumerate(res["trace"], 1):
            st.markdown(f"**{i}. {title}:** {detail}")


def render_history_entries(entries: list[dict]):
    if not entries:
        st.info("No analyses saved yet. Ask a question on the Analyze tab.")
    for e in entries:
        with st.expander(f"{fmt_time(e.get('timestamp'))} · {e.get('user_question', '')}"):
            st.caption(f"Dataset: {e.get('dataset_name')} · Analysis type: {e.get('analysis_type')}")
            st.markdown("**Answer**")
            st.write(e.get("answer", ""))
            if e.get("insights"):
                st.markdown("**Insights**")
                for insight in e["insights"]:
                    st.markdown(f"- {insight}")
            if e.get("recommendation"):
                st.markdown("**Recommendation**")
                st.write(e["recommendation"])


# --------------------------------------------------------------------------- page
init_state()
gemini = get_gemini()
if st.session_state.history is None:
    refresh_history()

with st.sidebar:
    st.title("🧭 DataPilot AI")
    st.caption("Upload data. Ask questions. Let an AI agent analyze it.")

    uploaded = st.file_uploader("Upload a CSV file", type=["csv"])
    if uploaded is not None:
        key = (uploaded.name, uploaded.size)
        if st.session_state.last_upload_key != key:
            st.session_state.last_upload_key = key
            try:
                set_dataset(load_csv(uploaded.getvalue()), uploaded.name)
            except DataLoadError as exc:
                st.session_state.df, st.session_state.dataset_name = None, None
                st.session_state.load_error = str(exc)
    if st.button("Use sample dataset (sales.csv)"):
        try:
            set_dataset(load_csv(SAMPLE_PATH.read_bytes()), "sales.csv")
        except (OSError, DataLoadError):
            st.session_state.load_error = "The sample dataset could not be loaded."
    if st.session_state.load_error:
        st.error(st.session_state.load_error)

    st.subheader("Dataset information")
    if st.session_state.df is not None:
        d = st.session_state.df
        st.write(f"**{st.session_state.dataset_name}**")
        st.caption(f"{len(d):,} rows × {d.shape[1]} columns")
    else:
        st.caption("No dataset loaded.")

    st.subheader("Analysis history")
    if st.session_state.history:
        for entry in st.session_state.history[:5]:
            st.caption(f"• {entry.get('user_question', '')}")
    else:
        st.caption("No history yet.")
    if st.button("Clear history"):
        st.session_state.local_history = []
        try:
            fs.clear_history()
        except fs.FirestoreError as exc:
            st.session_state.save_warning = str(exc)
        refresh_history()
        st.rerun()

    if not gemini.available:
        st.warning("GEMINI_API_KEY is not set. Analyses still work, but without AI explanations.")

st.title("DataPilot AI")
st.caption("Agentic AI-powered data analysis")

tab_analyze, tab_history = st.tabs(["Analyze", "History"])

with tab_analyze:
    df = st.session_state.df
    if df is None:
        st.info("Upload a CSV file in the sidebar, or click **Use sample dataset**, to get started.")
    else:
        render_dataset(df)
        st.divider()
        st.subheader("Ask your data anything")
        with st.form("ask_form"):
            question = st.text_input(
                "Your question",
                placeholder="Example: Which product generated the highest revenue?",
                label_visibility="collapsed",
            )
            submitted = st.form_submit_button("Analyze")

        if submitted:
            if not question.strip():
                st.warning("Please type a question first.")
            else:
                with st.spinner("The agent is analyzing your data..."):
                    res = run_agent(question.strip(), df, gemini)
                st.session_state.result, st.session_state.result_question = res, question.strip()
                if res["status"] == "ok":
                    save_history({
                        "user_question": question.strip(),
                        "dataset_name": st.session_state.dataset_name,
                        "analysis_type": res["plan"]["intent"],
                        "answer": res["explanation"]["answer"],
                        "insights": res["explanation"]["insights"],
                        "recommendation": res["explanation"]["recommendation"],
                    })
                else:
                    st.session_state.save_warning = None

        if st.session_state.result is not None:
            st.markdown(f"**Question:** {st.session_state.result_question}")
            render_result(st.session_state.result)
            if st.session_state.save_warning:
                st.warning(f"Could not save to Firestore. {st.session_state.save_warning}")

with tab_history:
    st.subheader("Previous analyses")
    if st.button("Refresh history"):
        refresh_history()
    if st.session_state.history_error:
        st.warning(st.session_state.history_error + " Showing this session's history only.")
    render_history_entries(st.session_state.history or [])
